{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNHjWbc7wp5eB5LQsyXoCri",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Santosdevbjj/analiseRiscosAtrasoObras/blob/main/Notebooks/gerar_dados.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "Rzb7y9l06NFX"
      },
      "outputs": [],
      "source": [
        "\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "from faker import Faker\n",
        "import random\n",
        "\n",
        "fake = Faker('pt_BR')\n",
        "np.random.seed(42)\n",
        "random.seed(42)  # Garantir reprodutibilidade também no random\n",
        "\n",
        "# Configurações\n",
        "NUM_OBRAS = 50\n",
        "NUM_FORNECEDORES = 20\n",
        "\n",
        "# 1. Gerar Obras\n",
        "obras = []\n",
        "cidades = ['Belo Horizonte', 'São Paulo', 'Rio de Janeiro', 'Curitiba', 'Salvador']\n",
        "\n",
        "for i in range(NUM_OBRAS):\n",
        "    obras.append({\n",
        "        'id_obra': f'MRV-{100+i}',\n",
        "        'nome_empreendimento': f'Residencial {fake.street_name()}',\n",
        "        'cidade': random.choice(cidades),\n",
        "        'orcamento_estimado': round(random.uniform(5_000_000, 20_000_000), 2),\n",
        "        'data_inicio_prevista': fake.date_between(start_date='-1y', end_date='today')\n",
        "    })\n",
        "\n",
        "df_obras = pd.DataFrame(obras)\n",
        "df_obras['data_inicio_prevista'] = pd.to_datetime(df_obras['data_inicio_prevista'])\n",
        "\n",
        "# 2. Gerar Fornecedores\n",
        "fornecedores = []\n",
        "for i in range(NUM_FORNECEDORES):\n",
        "    fornecedores.append({\n",
        "        'id_fornecedor': f'FORN-{i+1}',\n",
        "        'nome': fake.company(),\n",
        "        'rating_confiabilidade': round(random.uniform(1, 5), 1) # 1 a 5 estrelas\n",
        "    })\n",
        "\n",
        "df_fornecedores = pd.DataFrame(fornecedores)\n",
        "\n",
        "# 3. Gerar Atividades e Suprimentos (Com correlação de atraso)\n",
        "atividades = []\n",
        "suprimentos = []\n",
        "\n",
        "etapas_materiais = {\n",
        "    'Fundação': ['Cimento', 'Brita'],\n",
        "    'Estrutura': ['Aço', 'Madeira'],\n",
        "    'Acabamento': ['Piso', 'Tintas', 'Revestimento']\n",
        "}\n",
        "\n",
        "for idx, obra in df_obras.iterrows():\n",
        "    for etapa, materiais in etapas_materiais.items():\n",
        "        id_atv = f\"{obra['id_obra']}_{etapa}\"\n",
        "\n",
        "        # Escolhe um fornecedor aleatório\n",
        "        forn = df_fornecedores.sample(1).iloc[0]\n",
        "\n",
        "        # LÓGICA DE NEGÓCIO:\n",
        "        # - Se rating < 3, chance de atraso é 70%\n",
        "        # - Se orçamento > 15 milhões, chance de atraso aumenta em 20%\n",
        "        atraso_prob = 0.7 if forn['rating_confiabilidade'] < 3 else 0.2\n",
        "        if obra['orcamento_estimado'] > 15_000_000:\n",
        "            atraso_prob += 0.2\n",
        "\n",
        "        atraso_suprimento = 1 if random.random() < atraso_prob else 0\n",
        "        dias_atraso = random.randint(10, 30) if atraso_suprimento == 1 else 0\n",
        "\n",
        "        atividades.append({\n",
        "            'id_atividade': id_atv,\n",
        "            'id_obra': obra['id_obra'],\n",
        "            'etapa': etapa,\n",
        "            'dias_atraso': dias_atraso,\n",
        "            'status': 'Atrasado' if dias_atraso > 0 else 'No Prazo'\n",
        "        })\n",
        "\n",
        "        # Cada etapa pode ter múltiplos materiais\n",
        "        for material in materiais:\n",
        "            suprimentos.append({\n",
        "                'id_obra': obra['id_obra'],\n",
        "                'id_atividade': id_atv,\n",
        "                'id_fornecedor': forn['id_fornecedor'],\n",
        "                'material': material,\n",
        "                'atrasou_entrega': atraso_suprimento\n",
        "            })\n",
        "\n",
        "df_atividades = pd.DataFrame(atividades)\n",
        "df_suprimentos = pd.DataFrame(suprimentos)\n",
        "\n",
        "# Salvar tudo em CSV no diretório atual\n",
        "df_obras.to_csv('obras.csv', index=False)\n",
        "df_fornecedores.to_csv('fornecedores.csv', index=False)\n",
        "df_atividades.to_csv('atividades.csv', index=False)\n",
        "df_suprimentos.to_csv('suprimentos.csv', index=False)\n",
        "\n",
        "print(\"✅ Dados fictícios da MRV gerados com sucesso!\")"
      ]
    }
  ]
}