TEXTS = {
    "pt": {
        "flag": "🇧🇷",
        "start": (
            "🏗️ **CCBJJ Engenharia & Inteligência**\n"
            "Bem-vindo ao terminal de análise preditiva.\n\n"
            "Por favor, selecione seu idioma:"
        ),
        "help": (
            "📘 **Guia de Comandos**\n"
            "/start - Iniciar e selecionar idioma\n"
            "/help - Exibir este guia\n"
            "/language - Alterar idioma\n"
            "/status - Integridade do sistema\n"
            "/settings - Alterar fonte (CSV/Supabase)\n"
            "/about - Sobre a CCBJJ\n\n"
            "📍 **Para analisar:** Digite o ID da obra (ex: `CCBJJ-100`)"
        ),
        "about": (
            "🏗️ **CCBJJ Engenharia & Inteligência de Risco**\n\n"
            "Soluções em análise preditiva aplicadas à construção civil.\n"
            "Foco em risco, cronograma e tomada de decisão baseada em dados.\n\n"
            "_Desenvolvido por Sergio Luiz dos Santos_"
        ),
        "language_changed": "✅ Idioma alterado para Português 🇧🇷",
        "infra_select": (
            "🔌 **Configuração de Infraestrutura**\n"
            "Selecione a fonte de dados para as análises de IA:"
        ),
        "mode_changed": "✅ Infraestrutura definida para: ",
        "health_ok": "🚀 Sistema operando com 100% de integridade.",
        "status": "✅ Sistema Online (Render Cloud)\nFuso: Brasília (BRT)",
        "example_msg": "📝 **Exemplo Automático:**\nID: `CCBJJ-107`\nStatus: Analisando parâmetros climáticos e logísticos...",
        "not_found": "❌ ID da obra não localizado no ",
        "pdf_title": "RELATÓRIO DE INTELIGÊNCIA DE RISCO",
        "pdf_footer": "Este relatório foi gerado automaticamente pela IA da CCBJJ Engenharia.",
        "analysis_header": "Detalhamento da Análise:",
        "chart_caption": "📈 **Gráfico de Dispersão de Risco:** {id_obra}\nLegenda: O gráfico indica o desvio projetado em relação à linha de base zero.",
        "wait_msg": "🤖 **Processando análise preditiva...**",
        "risk_explanation": (
            "O modelo Random Forest identificou um risco estimado de **{risco:.1f} dias** "
            "de impacto no cronograma com base nos dados históricos da base {modo}."
        )
    },

    "en": {
        "flag": "🇺🇸",
        "start": (
            "🏗️ **CCBJJ Engineering & Intelligence**\n"
            "Welcome to the predictive analysis terminal.\n\n"
            "Please select your language:"
        ),
        "help": (
            "📘 **Command Guide**\n"
            "/start - Start and select language\n"
            "/help - Show this guide\n"
            "/language - Change language\n"
            "/status - System integrity\n"
            "/settings - Change data source (CSV/Supabase)\n"
            "/about - About CCBJJ\n\n"
            "📍 **To analyze:** Type the project ID (e.g., `CCBJJ-100`)"
        ),
        "about": (
            "🏗️ **CCBJJ Engineering & Risk Intelligence**\n\n"
            "Predictive analytics solutions for construction risk management.\n"
            "Focused on risk, scheduling, and data-driven decision making.\n\n"
            "_Developed by Sergio Luiz dos Santos_"
        ),
        "language_changed": "✅ Language changed to English 🇺🇸",
        "infra_select": (
            "🔌 **Infrastructure Setup**\n"
            "Select the data source for AI analysis:"
        ),
        "mode_changed": "✅ Infrastructure defined to: ",
        "health_ok": "🚀 System operating with 100% integrity.",
        "status": "✅ System Online (Render Cloud)\nTimezone: Brasilia (BRT)",
        "example_msg": "📝 **Automatic Example:**\nID: `CCBJJ-107`\nStatus: Analyzing climate and logistic parameters...",
        "not_found": "❌ Project ID not found in ",
        "pdf_title": "RISK INTELLIGENCE REPORT",
        "pdf_footer": "This report was automatically generated by CCBJJ Engineering AI.",
        "analysis_header": "Analysis Details:",
        "chart_caption": "📈 **Risk Dispersion Chart:** {id_obra}\nLegend: The chart indicates the projected deviation from the zero baseline.",
        "wait_msg": "🤖 **Processing predictive analysis...**",
        "risk_explanation": (
            "The Random Forest model identified an estimated risk of **{risco:.1f} days** "
            "of schedule impact based on historical data from {modo}."
        )
    }
}
